# Duels by Dartanman
# Don't edit kits in the file... unless you're particularly confident in your ability to read/write in Base64!
Kits:
  default:
  - "rO0ABXcEAAAAJHNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
    \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
    \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmpl\r\
    \nY3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAA\r\
    \nAAN0AAI9PXQAAXZ0AAR0eXBldXEAfgAGAAAAA3QAHm9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1T\r\
    \ndGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5n\r\
    \nLk51bWJlcoaslR0LlOCLAgAAeHAAAAqqdAAKSVJPTl9TV09SRHNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
    \nAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AAxzcQB+AA0AAAqqdAALRklTSElOR19ST0Rz\r\
    \ncQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgAMc3EAfgAN\r\
    \nAAAKqnQACElST05fQVhFc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4A\r\
    \nBgAAAANxAH4ADHNxAH4ADQAACqp0AANCT1dwcHBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\r\
    \nAH4ACXEAfgAKdAAGYW1vdW50dXEAfgAGAAAABHEAfgAMc3EAfgANAAAKqnQADEdPTERFTl9BUFBM\r\
    \nRXNxAH4ADQAAAANzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ACZ1cQB+\r\
    \nAAYAAAAEcQB+AAxzcQB+AA0AAAqqdAALQ09PS0VEX0JFRUZzcQB+AA0AAABAc3EAfgAAc3EAfgAD\r\
    \ndXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAmdXEAfgAGAAAABHEAfgAMc3EAfgANAAAKqnQA\r\
    \nBUFSUk9XcQB+ADFwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcA==\r\n"
  - "rO0ABXcEAAAABHNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
    \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
    \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmpl\r\
    \nY3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAA\r\
    \nAAN0AAI9PXQAAXZ0AAR0eXBldXEAfgAGAAAAA3QAHm9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1T\r\
    \ndGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5n\r\
    \nLk51bWJlcoaslR0LlOCLAgAAeHAAAAqqdAAKSVJPTl9CT09UU3NxAH4AAHNxAH4AA3VxAH4ABgAA\r\
    \nAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AAxzcQB+AA0AAAqqdAANSVJPTl9MRUdHSU5H\r\
    \nU3NxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AAxzcQB+\r\
    \nAA0AAAqqdAAPSVJPTl9DSEVTVFBMQVRFc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlx\r\
    \nAH4ACnVxAH4ABgAAAANxAH4ADHNxAH4ADQAACqp0AAtJUk9OX0hFTE1FVA==\r\n"
Arenas: