name: Duels
author: Dartanman
main: main.dartanman.duels.Main
version: 3.0.0
api-version: 1.16
commands:
  duel:
    description: Duels base command
    usage: /<command>
    aliases: [duels, 1v1, 1v1duel, duel1v1]