# Duels by Dartanman
# Don't edit kits in the file... unless you're particularly confident in your ability to read/write in Base64!
Messages:
  Countdown: "&aThe Duel begins in <seconds> second(s)!"
  Unknown-Command: '&cUnknown command. Try &e/duels help&c!'
  Incorrect-Args: '&cIncorrect args. Try &e<suggestion>&c!'
  No-Available-Arena: '&cUnfortunately, no Duel Arenas are available right now. Try again later!'
  Arena-Not-Available: '&cUnfortunately, that particular arena is not available right now. Pick another or try again later!'
  Joined-Arena: '&aYou have joined the Duel Arena called &e<arena_name>'
  Player-Left-Cancelled: '&cA player has left the duel and the countdown has been cancelled.'
  Invalid-Arena-Id: '&c<arg> is not a valid arena id (either it does not exist or is a name, not an id)'
  Arena-List-Format: '&9<id> &f- &e<arena_name> &f- &6<state>'
  Arena-Created: '&aArena &e<arena_name> &acreated! &e&lRemember to set its lobby and spawn locations!'
  Arena-Not-Finished: '&cArena is not finished! Ensure it has both spawnpoints and a lobby location set!'
  Arena-Finished: '&aArena has been finished and is now joinable!'
  Help-Menu:
    - '&9Duels Help Menu&f:'
    - '&6/duels help&f: &eDisplay this help menu'
    - '&6/duels join [id]&f: &eJoin an available arena or the arena with the given id'
    - '&6/duels listarenas&f: &eList all arenas'
    - '&6/duels createarena <arena name>&f: &eCreate a new arena called <arena name>'
    - '&6/duels setlobby &7or &6setspawn1 &7or &6setspawn2&f: &eSet the given location of the arena you are currently making'
    - '&6/duels finisharena&f: &eSave and finish the arena you are currently making'


  # OLD OLD OLD OLD OLD OLD OLD OLD OLD OLD OLD OLD
  WinMessage: '&aYou won the duel!'
  LoseMessage: '&cYou lost the duel!'
  PrepareToDuelMessage: '&1PREPARE TO DUEL!'
  NotAPlayerMessage: '&cYou must be a Player to do that!'
  NoPermissionMessage: '&cInsufficient permissions.'
  AttemptJoinMessage: '&aAttempting to join a duel...'
  JoinedMessage: '&aSuccessfully joined <arena>!'
  IncorrectArgsMessage: '&cIncorrect args! Try &e/duels help'
  CreateKitMessage: '&aSuccessfully created the kit called &e<kit>&a!'
  NoKitByThatNameMessage: '&cThere is no kit called &e<kit>&c!'
  SelectKitMessage: '&aSelected &e<kit>&a!'
  DeleteKitMessage: '&aSuccessfully deleted &e<kit>&a!'
  CreateArenaMessage: '&aSuccessfully created an arena! Do not forget to set its spawns!'
  NoArenaByThatNameMessage: '&cThere is no arena called &e<arena>&c!'
  ThatArenaIsFullMessage: '&cThat arena is not available right now! (It is full)'
  AlreadyInDuelMessage: '&cYou are already in a duel! You cannot join another one yet. Finish your current duel first!'
  NotInDuelMessage: '&cYou are not in a Duel, so you cannot leave one!'
  LeftDuelMessage: '&aYou left the duel.'
  CannotLeaveDuelMessage: '&cThe duel has already started! You cannot leave now!'
Kits:
  default:
  - "rO0ABXcEAAAAJHNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
    \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
    \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmpl\r\
    \nY3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAA\r\
    \nAAN0AAI9PXQAAXZ0AAR0eXBldXEAfgAGAAAAA3QAHm9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1T\r\
    \ndGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5n\r\
    \nLk51bWJlcoaslR0LlOCLAgAAeHAAAAqqdAAKSVJPTl9TV09SRHNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
    \nAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AAxzcQB+AA0AAAqqdAALRklTSElOR19ST0Rz\r\
    \ncQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgAMc3EAfgAN\r\
    \nAAAKqnQACElST05fQVhFc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4A\r\
    \nBgAAAANxAH4ADHNxAH4ADQAACqp0AANCT1dwcHBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\r\
    \nAH4ACXEAfgAKdAAGYW1vdW50dXEAfgAGAAAABHEAfgAMc3EAfgANAAAKqnQADEdPTERFTl9BUFBM\r\
    \nRXNxAH4ADQAAAANzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ACZ1cQB+\r\
    \nAAYAAAAEcQB+AAxzcQB+AA0AAAqqdAALQ09PS0VEX0JFRUZzcQB+AA0AAABAc3EAfgAAc3EAfgAD\r\
    \ndXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAmdXEAfgAGAAAABHEAfgAMc3EAfgANAAAKqnQA\r\
    \nBUFSUk9XcQB+ADFwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcA==\r\n"
  - "rO0ABXcEAAAABHNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
    \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
    \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmpl\r\
    \nY3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAA\r\
    \nAAN0AAI9PXQAAXZ0AAR0eXBldXEAfgAGAAAAA3QAHm9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1T\r\
    \ndGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5n\r\
    \nLk51bWJlcoaslR0LlOCLAgAAeHAAAAqqdAAKSVJPTl9CT09UU3NxAH4AAHNxAH4AA3VxAH4ABgAA\r\
    \nAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AAxzcQB+AA0AAAqqdAANSVJPTl9MRUdHSU5H\r\
    \nU3NxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AAxzcQB+\r\
    \nAA0AAAqqdAAPSVJPTl9DSEVTVFBMQVRFc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlx\r\
    \nAH4ACnVxAH4ABgAAAANxAH4ADHNxAH4ADQAACqp0AAtJUk9OX0hFTE1FVA==\r\n"
Arenas:
  0:
    Name: DefaultArena
    Countdown-Seconds: 30
    Spawn-One:
      World: world
      X: 0
      Y: 100
      Z: 0
      Yaw: 0
      Pitch: 0
    Spawn-Two:
      World: world
      X: 0
      Y: 100
      Z: 20
      Yaw: 180
      Pitch: 0
    Lobby:
      World: world
      X: 100
      Y: 100
      Z: 100
      Yaw: 0
      Pitch: 0