name: Duels
author: Dartanman
main: me.dartanman.duels.Duels
softdepend: [PlaceholderAPI, Multiverse-Core]
version: ${project.version}
api-version: 1.20
commands:
  duel:
    description: Duels base command
    usage: /<command>
    aliases: [duels, 1v1, 1v1duel, duel1v1]