name: Duels
author: Dartanman
main: me.dartanman.duels.Duels
version: 3.1.2
api-version: 1.17
commands:
  duel:
    description: Duels base command
    usage: /<command>
    aliases: [duels, 1v1, 1v1duel, duel1v1]